In [17]:
import pandas  as pd
import numpy as np

In [33]:
# create metadata data

data = pd.DataFrame({})
data["series_uid"] = [i for i in range(2,10)]
data["study_id"] = ["study."+ str(i) for i in range(5001, 5009)]
data["series_desc"] =np.random.choice(["ROI", "Full"], size=len(data))
data["number_of_files"] =np.random.choice([1, 2], size=len(data))
data["file_location"] = ["/files-loc/loc."+ str(i) for i in range(2,10)]

meta_df = pd.DataFrame(data)
meta_df

   series_uid    study_id series_desc  number_of_files     file_location
0           2  study.5001         ROI                2  /files-loc/loc.2
1           3  study.5002        Full                2  /files-loc/loc.3
2           4  study.5003        Full                2  /files-loc/loc.4
3           5  study.5004         ROI                1  /files-loc/loc.5
4           6  study.5005        Full                2  /files-loc/loc.6
5           7  study.5006         ROI                2  /files-loc/loc.7
6           8  study.5007         ROI                1  /files-loc/loc.8
7           9  study.5008         ROI                2  /files-loc/loc.9

In [48]:
file_paths = []
for loc, files in zip (meta_df["file_location"], meta_df["number_of_files"]):
    for file in range(files):
        file_paths.append(loc + "." + str(file))
len(file_paths)
file_paths

['/files-loc/loc.2.0',
 '/files-loc/loc.2.1',
 '/files-loc/loc.3.0',
 '/files-loc/loc.3.1',
 '/files-loc/loc.4.0',
 '/files-loc/loc.4.1',
 '/files-loc/loc.5.0',
 '/files-loc/loc.6.0',
 '/files-loc/loc.6.1',
 '/files-loc/loc.7.0',
 '/files-loc/loc.7.1',
 '/files-loc/loc.8.0',
 '/files-loc/loc.9.0',
 '/files-loc/loc.9.1']

In [50]:
# create description data

des_data = pd.DataFrame({})
des_data["patient"] = ["P000"+ str(i) for i in range(38,46)]
des_data["pathology"] = np.random.choice(["BENIGN_WITHOUT_CALLBACK","BENIGN","MALIGNANT"], size=len(data))
des_data["series_uid"] = [i for i in range(2,10)]
des_data["study_id"] = ["study."+ str(i) for i in range(5001, 5009)]
des_data["series_desc"] = np.random.choice(["ROI", "Full"], size=len(data))
des_data["file_loc"] = ["/files-loc/loc."+ str(i) for i in range(2,10)]

desc_df = pd.DataFrame(des_data)
desc_df

,patient,pathology,series_uid,study_id,series_desc,file_loc
0,P00038,MALIGNANT,2,study.5001,Full,/files-loc/loc.2
1,P00039,BENIGN_WITHOUT_CALLBACK,3,study.5002,Full,/files-loc/loc.3
2,P00040,MALIGNANT,4,study.5003,ROI,/files-loc/loc.4
3,P00041,MALIGNANT,5,study.5004,Full,/files-loc/loc.5
4,P00042,BENIGN_WITHOUT_CALLBACK,6,study.5005,Full,/files-loc/loc.6
5,P00043,MALIGNANT,7,study.5006,Full,/files-loc/loc.7
6,P00044,BENIGN,8,study.5007,Full,/files-loc/loc.8
7,P00045,BENIGN_WITHOUT_CALLBACK,9,study.5008,ROI,/files-loc/loc.9